 let mockdata = [
  {
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '123-456-7890',
    email: 'john.doe@example.com',
    pickup: '123 Main St',
    passenger: '1',
    purpose: 'Medical',
    trip: 'Round Trip',
    date: '2024-06-08',
    pickupTime: '10:00 AM'
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    phoneNumber: '098-765-4321',
    email: 'jane.smith@example.com',
    pickup: '789 Oak St',
    passenger: '2',
    purpose: 'Business',
    trip: 'One Way',
    date: '2024-06-09',
    pickupTime: '2:00 PM'
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    phoneNumber: '555-123-4567',
    email: 'alice.johnson@example.com',
    pickup: '246 Birch St',
    passenger: '1',
    purpose: 'Shopping',
    trip: 'Round Trip',
    date: '2024-06-10',
    pickupTime: '9:00 AM'
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    phoneNumber: '555-123-4567',
    email: 'alice.johnson@example.com',
    pickup: '246 Birch St',
    passenger: '1',
    purpose: 'Shopping',
    trip: 'Round Trip',
    date: '2024-06-10',
    pickupTime: '9:00 AM'
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    phoneNumber: '555-123-4567',
    email: 'alice.johnson@example.com',
    pickup: '246 Birch St',
    passenger: '1',
    purpose: 'Shopping',
    trip: 'Round Trip',
    date: '2024-06-10',
    pickupTime: '9:00 AM'
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    phoneNumber: '555-123-4567',
    email: 'alice.johnson@example.com',
    pickup: '246 Birch St',
    passenger: '1',
    purpose: 'Shopping',
    trip: 'Round Trip',
    date: '2024-06-10',
    pickupTime: '9:00 AM'
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    phoneNumber: '555-123-4567',
    email: 'alice.johnson@example.com',
    pickup: '246 Birch St',
    passenger: '1',
    purpose: 'Shopping',
    trip: 'Round Trip',
    date: '2024-06-10',
    pickupTime: '9:00 AM'
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    phoneNumber: '555-123-4567',
    email: 'alice.johnson@example.com',
    pickup: '246 Birch St',
    passenger: '1',
    purpose: 'Shopping',
    trip: 'Round Trip',
    date: '2024-06-10',
    pickupTime: '9:00 AM'
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    phoneNumber: '555-123-4567',
    email: 'alice.johnson@example.com',
    pickup: '246 Birch St',
    passenger: '1',
    purpose: 'Shopping',
    trip: 'Round Trip',
    date: '2024-06-10',
    pickupTime: '9:00 AM'
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    phoneNumber: '555-123-4567',
    email: 'alice.johnson@example.com',
    pickup: '246 Birch St',
    passenger: '1',
    purpose: 'Shopping',
    trip: 'Round Trip',
    date: '2024-06-10',
    pickupTime: '9:00 AM'
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    phoneNumber: '555-123-4567',
    email: 'alice.johnson@example.com',
    pickup: '246 Birch St',
    passenger: '1',
    purpose: 'Shopping',
    trip: 'Round Trip',
    date: '2024-06-10',
    pickupTime: '9:00 AM'
  }
];
 export default mockdata;
